//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticketing_System.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerDetails
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FullName { get; set; }
        public string TicketType { get; set; }
        public string TicketName { get; set; }
        public Nullable<int> TotalPeople { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<int> Vat { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
